CREATE TABLE ALLTEAM(
	ROT INT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	AREA VARCHAR(20) NOT NULL, 
)

--ASIAN NATION TEAM
INSERT INTO	dbo.ALLTEAM	VALUES  ( 1,'AUTRALIA','AFC'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 2,'IRAN','AFC');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 3,'JAPAN','AFC');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 4,'SAUDI ARABIA','AFC'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 5,'SOUTH KOREA','AFC'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 6,'CHINA','AFC'); 

--CAF NATION TEAM
INSERT INTO	dbo.ALLTEAM	VALUES  ( 1,'EGYPT','CAF'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 2,'MOROCCO','CAF');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 3,'NIGERIA','CAF');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 4,'SENEGAL','CAF'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 5,'TUNISIA','CAF');

--CONCACAF--
INSERT INTO	dbo.ALLTEAM	VALUES  ( 1,'COSTA RICA','CONCACAF'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 2,'MEXICO','CONCACAF');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 3,'NIGERIA','CONCACAF');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 4,'URUGUAY','CONCACAF');

--CONMEBOL

INSERT INTO	dbo.ALLTEAM	VALUES  ( 1,'ARGENTINA','CONMEBOL'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 2,'BRAZIL','CONMEBOL');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 3,'COLOMBIA','CONMEBOL');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 4,'PERU','CONMEBOL'); 


--OFC

INSERT INTO	dbo.ALLTEAM	VALUES  ( 1,'GHANA','OFC');

--UEFA

INSERT INTO	dbo.ALLTEAM	VALUES  ( 1,'BELGIUM','UEFA'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 2,'CROATIA','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 3,'DENMARK','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 4,'ENGLAND','UEFA'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 5,'FRANCE','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 6,'GERMANY','UEFA'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 7,'ICELAND','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 8,'POLAND','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 9,'PORTUGAL','UEFA'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 10,'RUSSIA','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 11,'SERBIA','UEFA'); 
INSERT INTO	dbo.ALLTEAM	VALUES  ( 12,'SPAIN','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 13,'SWEDEN','UEFA');
INSERT INTO	dbo.ALLTEAM	VALUES  ( 14,'SWITZERLAND','UEFA'); 


